### PR TITLE
Update for the linking documentation

### PR DESCRIPTION
**Pull request by snilsn**
I added some plots and explanations I originally did for my tutorial on the tracking methods to the linking documentation.

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [x] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [ ] Have you added NumPy docstrings for newly added functions? 
* [x] Have you formatted your code using black? 
* [ ] If you have introduced a new functionality, have you added adequate unit tests?
* [ ] Have all tests passed in your local clone? 
* [ ] If you have introduced a new functionality, have you added an example notebook?
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged?

### CODE REVIEW

**Review by freemansw1 — APPROVED** [review]
I think this is a great change; thanks for adding it.

**Comment by snilsn** [comment]
I deleted a duplicate picture and corrected a typo. The updated page of the documentation can be found here: https://tobac--210.org.readthedocs.build/en/210/linking.html

**Review by JuliaKukulies — APPROVED** [review]
Looks great! This is a really helpful contribution @snilsn, approved!

**Comment by freemansw1** [comment]
With two approving reviews, I'm happy to merge if you're happy for it to be merged @snilsn

**Comment by snilsn** [comment]
@freemansw1 After some feedback from @fsenf I increased some font sizes. Happy to merge now!

**Pull request merged**
