### PR TITLE
Introducing pylint in our workflow 

### PR DESCRIPTION
**Pull request by JuliaKukulies**
This PR addresses #273 and adds a `pylint` check in the github actions. `pylint` is run on PRs to the `RC_*` branch  and the resulting score is posted as a comment to the respective PR. The full length output of the linting can be seen in the details of the action. 

In addition, I fixed the unused import issues in our modules. The resulting score for the entire tobac package  is currently 8.78/10 (if conventions are disabled ) and 6.72/10 if not -- not so bad actually. 

What I did not manage to implement, though, was to compare the score of PRs to previous scores (i.e. the score of the current `main`. This would be valuable because it would tell contributors if the score has deteriorated. Given that the python environment is re-installed with every action, the previous scores are not stored. I tried both caching of the python environment as well as running `pylint` on `main` within the steps of an action, but both did not seem to work. Any ideas on how to achieve this? 

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [x] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [ ] Have you added NumPy docstrings for newly added functions? N/A
* [ ] Have you formatted your code using black? N/A
* [ ] If you have introduced a new functionality, have you added adequate unit tests? N/A
* [x] Have all tests passed in your local clone? 
* [ ] If you have introduced a new functionality, have you added an example notebook? N/A
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged?

### CODE REVIEW

**Comment by JuliaKukulies** [comment]
OK, I figured this did not work out as in my fork due to [permissions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) granted to the GITHUB_TOKEN. Is it reasonable to adjust these, in order to post the score as comment or are you aware of another way?

**Comment by freemansw1** [comment]
> OK, I figured this did not work out as in my fork due to [permissions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) granted to the GITHUB_TOKEN. Is it reasonable to adjust these, in order to post the score as comment or are you aware of another way?

I'm happy for us to adjust these. For adding the coverage bot, I ended up doing my work in a branch of the main repo rather than on a personal fork; that might be helpful here?

**Comment by JuliaKukulies** [comment]
That's a good point @freemansw1, will do!

**Comment by freemansw1** [comment]
@JuliaKukulies Do you want this in v1.5.0, or are you happy to wait for a later release?

**Comment by JuliaKukulies** [comment]
@freemansw1 later release, thanks for asking! This is really not urgent and that will give me some time to figure out how to do that the smartest way

**Comment by w-k-jones** [comment]
Like #258 we can introduce workflow actions independently of releases, correct?

**Comment by JuliaKukulies** [comment]
> Like #258 we can introduce workflow actions independently of releases, correct?

That makes sense, yes!

**Comment by fsenf** [comment]
Hej all, this is also nearly ready! @fziegner has a nice working version there.

Workflow: Fabian is updating his PR onto Julias fork. After Julia has accepted this PR should be ready to be reviewed.

**Comment by JuliaKukulies** [comment]
@fziegner do you know why the linting fails here?

**Comment by fziegner** [comment]
From the comments earlier this year it looks like it was already changed but can you check if the Workflow has Write access? (https://stackoverflow.com/a/76199390)

**Comment by freemansw1** [comment]
> From the comments earlier this year it looks like it was already changed but can you check if the Workflow has Write access? (https://stackoverflow.com/a/76199390)

This was indeed changed, and I can confirm "Workflows have read and write permissions in the repository for all scopes."

**Comment by freemansw1** [comment]
OK, I think I figured out the issue. See my discussion in #373

**Comment by freemansw1** [comment]
We can either close this PR or modify it to just be the enhanced linting. Your choice, @fziegner @JuliaKukulies

**Pull request closed without merging**
