### PR TITLE
Update bulk statistics to use multiple fields correctly

### PR DESCRIPTION
**Pull request by w-k-jones**
Fixes `get_statistics_from_mask` to work with multiple field inputs correctly, resolving #364, and also solves the issue that was causing the jupyter notebook CI to fail

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [x] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [x] Have you added NumPy docstrings for newly added functions? 
* [x] Have you formatted your code using black? 
* [x] If you have introduced a new functionality, have you added adequate unit tests?
* [x] Have all tests passed in your local clone? 
* [x] If you have introduced a new functionality, have you added an example notebook?
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged?

### CODE REVIEW

**Review by freemansw1 — APPROVED** [review]
Thanks for doing this.

**Review by JuliaKukulies — APPROVED** [review]
Looks great, thanks for fixing this @w-k-jones!

**Comment by w-k-jones** [comment]
I updated the arguments order in bulk_statistics as discussed in #369, and also renamed the `statistics` keyword to `statistic` in feature_detection/segmentation to match that in `bulk_statistics`

**Comment by w-k-jones** [comment]
"Run failed: Jupyter Notebooks CI" 😡

**Comment by w-k-jones** [comment]
@JuliaKukulies @freemansw1 I've added numpy style broadcasting to `get_statistics`, as well as the ability for `get_statistics_from_mask` to pass fields without a time dimension (e.g. for area) without slicing. This came up as an issue when processing some of the statistics from the mcsmip data efficiently. The changes are quite straightforward, and I've added tests for both cases, but let me know if you want to re-review before merging.

I also have some ideas for how to handle 3D -> 2D field conversion (e.g. calculating the footprint of a 3D cloud object) that would fit into this framework, but that could also wait until after v1.5.2

**Comment by JuliaKukulies** [comment]
> @JuliaKukulies @freemansw1 I've added numpy style broadcasting to `get_statistics`, as well as the ability for `get_statistics_from_mask` to pass fields without a time dimension (e.g. for area) without slicing. This came up as an issue when processing some of the statistics from the mcsmip data efficiently. The changes are quite straightforward, and I've added tests for both cases, but let me know if you want to re-review before merging.
> 
> I also have some ideas for how to handle 3D -> 2D field conversion (e.g. calculating the footprint of a 3D cloud object) that would fit into this framework, but that could also wait until after v1.5.2

I have had a look and am happy for you to merge these changes! Nice also with the 3D to 2D conversion. Is that a matter of a few lines of code that can just be added in the bulk statistics function or a little more complicated? If it is more complicated I would say we wait until after v1.5.2

**Comment by w-k-jones** [comment]
I think it may be a bit more complicated as it conflicts with the broadcasting. I'll have a think, but it may be a case of waiting until after v1.5.2 and fixing it along with the area calculation for 3D fields in #333

**Review by freemansw1 — APPROVED** [review]
Thanks for the edits, @w-k-jones ! I'm happy for this to be merged (again)

**Pull request merged**
