### PR TITLE
Re-executed notebooks

### PR DESCRIPTION
**Pull request by lettlini**
* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [ ] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [ ] Have you added NumPy docstrings for newly added functions? 
* [ ] Have you formatted your code using black? 
* [ ] If you have introduced a new functionality, have you added adequate unit tests?
* [ ] Have all tests passed in your local clone? 
* [ ] If you have introduced a new functionality, have you added an example notebook?
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged? 

I have re-executed the `example/` notebooks (except for the cells creating the animations).

### CODE REVIEW

**Comment by w-k-jones** [comment]
Notebook output looks good

**Comment by w-k-jones** [comment]
The issue with the tests seems to be on the codecov.io end, so I'm happy for this to be merged unless you want a second review

**Comment by lettlini** [comment]
Alright thank you. If you took a quick look and it looked good to you, I don't think a second review is necessary.

**Review by freemansw1 — APPROVED** [review]
I'm happy with this.

**Comment by freemansw1** [comment]
A couple overall notes. First, the Codecov CI tends to fail every so often; this is a documented error and can be worked around by just re-running it. Not ideal, but it's not just us. Probably something to examine in the longer-term, but I largely like the Codecov integration. 

I think merging this PR with 1 review is fine given the fact that it's documentation, but I think we need to talk PR policies either in Oxford or at a future development meeting. Would probably be good to get something written down.

**Pull request merged**
