### PR TITLE
Fix CI issues due to old conda version

### PR DESCRIPTION
**Pull request by freemansw1**
This continues the work from #457 and fixes issues with a few of our CI workflows that broke from `miniconda` being depreciated. 

Note that this is a _PR to main_ per our policy of CI improvements

* [ ] Have you followed our guidelines in CONTRIBUTING.md? 
* [ ] Have you self-reviewed your code and corrected any misspellings? 
* [ ] Have you written documentation that is easy to understand?
* [ ] Have you written descriptive commit messages? 
* [ ] Have you added NumPy docstrings for newly added functions? 
* [ ] Have you formatted your code using black? 
* [ ] If you have introduced a new functionality, have you added adequate unit tests?
* [ ] Have all tests passed in your local clone? 
* [ ] If you have introduced a new functionality, have you added an example notebook?
* [ ] Have you kept your pull request small and limited so that it is easy to review? 
* [ ] Have the newest changes from this branch been merged?

### CODE REVIEW

**Comment by freemansw1** [comment]
The notebook CI is failing due to an upstream issue with pyart that has been fixed and will be released as part of their next version (https://github.com/ARM-DOE/pyart/pull/1623). As a temporary fix, I've copied their fix over to pin xarray versions to `<2024.10.0`. 

I have no clue what is happening to the lining workflow. I've tried to partially roll it back, but it seems to always grab the old version of the file. I'd appreciate some help here, if someone wants to take a look.

**Comment by freemansw1** [comment]
> I have no clue what is happening to the lining workflow. I've tried to partially roll it back, but it seems to always grab the old version of the file. I'd appreciate some help here, if someone wants to take a look.

Okay, apparently this is expected behavior: https://github.com/orgs/community/discussions/122045 . I suppose we just must trust that the CI will pass?

**Review by w-k-jones — APPROVED** [review]
Great, thanks for sorting this! Happy to merge and see if the linting works properly afterwards

**Review by JuliaKukulies — APPROVED** [review]
Yes OK, good to go from my side and merge this and see if the linting issue will fix itself. Thanks for fixing this, @freemansw1 !

**Pull request merged**
