### PR TITLE
Merge `RC_v1.5.0` into `main`

### PR DESCRIPTION
**Pull request by freemansw1**
This feels momentous. This PR will merge the v1.5.0 release candidate into `main`. 

Since I won't have another chance, some acknowledgments (and apologies if I've missed anyone): 

@JuliaKukulies @w-k-jones @kelcyno @fsenf : thanks as always for being lead developers with me. An absolute honor to work with you all. This has been a long, drawn-out process and we wouldn't be here without all of your contributions. 
@snilsn : thanks for coming in and getting so much done so quickly. I'm excited to see your future!
@lettlini : thanks for coming up with clever solutions to many of the problems we have neglected. You stepped up quickly and have some of the most clever code in the package.
@galexsky : without your need for and efforts to add in 3D and PBC, I don't think we get this released. I may not even be involved in *tobac* without that. 

To our steering committee, thanks for always providing good advice and for funding most (all?) of us throughout this process. *tobac* has been an absolute labor of love, and you have all been patient with us as we work on this instead of other work. 

To our users, thanks for being a much larger and involved group than I ever expected. You are the reason we keep working on this. 

Since serious work on v1.5.0 started in January 2022, the contributors to this version have earned 3 PhDs (with one just around the corner), at least 1 masters degree, have started or will start 4(?) new positions, have moved at least 4 times, and have stuck with *tobac* all the way.

Versions released since January 2022 have had a total of 6,222 downloads on conda-forge. Looking forward to seeing that number continue to grow.

### CODE REVIEW

**Comment by freemansw1** [comment]
We are never doing another release (barring perhaps the xarray transition) this large again, ha.

**Comment by w-k-jones** [comment]
Happy for this to be merged without approving reviews once all the tests have passed

Also thanks to you as well for all your hard work over the past year @freemansw1 ! Here's to smoother release cycles in the future aha

**Comment by JuliaKukulies** [comment]
Great job @freemansw1! Thanks to you for all the hard work that you put into this!

**Comment by kelcyno** [comment]
Great job Sean - this has been a long work in progress, happy for it to reach the finish line!

**Review by JuliaKukulies — APPROVED** [review]

**Review by kelcyno — APPROVED** [review]
I have nothing to add here - it looks good!

**Comment by freemansw1** [comment]
Of course the API docs break, ha!

**Comment by JuliaKukulies** [comment]
Thanks @kelcyno for approving so we do not have to bypass the current branch protection rules :) In general I think it makes sense to require an extra check whenever things are merged into `main`, but we can revisit this question in the future @w-k-jones ! We will probably not check much more except for - is it the right branch to be merged? and have all tests passed?

**Comment by JuliaKukulies** [comment]
> 


> Of course the API docs break, ha!

Oh no I cant believe that...

**Comment by freemansw1** [comment]
API docs are **fixed** so I will merge once tests pass.

**Comment by JuliaKukulies** [comment]
Please go ahead! Yay :)

**Pull request merged**
