### PR TITLE
V1.5.1 release updates

### PR DESCRIPTION
**Pull request by w-k-jones**
Update version number, changelog and notebooks for v1.5.1 release

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [x] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [x] Have you added NumPy docstrings for newly added functions? 
* [x] Have you formatted your code using black? 
* [x] If you have introduced a new functionality, have you added adequate unit tests?
* [x] Have all tests passed in your local clone? 
* [x] If you have introduced a new functionality, have you added an example notebook?
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged?

### CODE REVIEW

**Review by JuliaKukulies — APPROVED** [review]
Looks good - thanks for taking care of this hotfix, @w-k-jones! I assume that we should merge this before #323. 

One thing I noticed is that you called the new hotfix branch `RC_v1.5_hotfix` which has the same branch pattern that we use for the release candidates (`RC_v*`). That is not a big deal at all, but I just wanted to point out this because it means that the branch falls under the branch protection rules  for release candidates (2 reviews) now.

**Review by freemansw1 — APPROVED** [review]
Thanks for doing this, Will.

**Comment by w-k-jones** [comment]
> One thing I noticed is that you called the new hotfix branch `RC_v1.5_hotfix` which has the same branch pattern that we use for the release candidates (`RC_v*`). That is not a big deal at all, but I just wanted to point out this because it means that the branch falls under the branch protection rules for release candidates (2 reviews) now.

I did that specifically so that the branch protection rules would apply, but perhaps we should consider in future a different workflow for hotfixes?

**Comment by JuliaKukulies** [comment]
> > One thing I noticed is that you called the new hotfix branch `RC_v1.5_hotfix` which has the same branch pattern that we use for the release candidates (`RC_v*`). That is not a big deal at all, but I just wanted to point out this because it means that the branch falls under the branch protection rules for release candidates (2 reviews) now.
> 
> I did that specifically so that the branch protection rules would apply, but perhaps we should consider in future a different workflow for hotfixes?

Ah OK :)  I thought that we had agreed at some point that one review suffices for hotfixes, but we can re-evaluate if this really should be the case.

**Pull request merged**
