### PR TITLE
Add matrix CI Tests on multiple Python versions and OS versions

### PR DESCRIPTION
**Pull request by freemansw1**
This PR adds matrix testing (a matrix of Linux, MacOS, Windows for Pythons 3.8, 3.9, 3.10, 3.11). Right now, this is configured to run on the primary tobac repo (i.e., this one) only, and not on fork repos to save computation time. 

Note that this has indicated a bug/issue in testing with `int32` vs `int64` datatypes on Windows. I have a windows computer at home; I will have to debug there. 

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [ ] Have you self-reviewed your code and corrected any misspellings? 
* [ ] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [ ] Have you added NumPy docstrings for newly added functions? 
* [x] Have you formatted your code using black? 
* [ ] If you have introduced a new functionality, have you added adequate unit tests?
* [ ] Have all tests passed in your local clone? 
* [ ] If you have introduced a new functionality, have you added an example notebook?
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged?

### CODE REVIEW

**Review by w-k-jones — APPROVED** [review]
Very nice addition! Hopefully the fix for windows should be quite straightforward

**Review by JuliaKukulies — APPROVED** [review]
Nice, this is very useful, @freemansw1 ! Thanks for adding this! And hopefully it will not be to hard to fix the windows issue.

**Comment by freemansw1** [comment]
I fixed the Windows bugs through keeping data types constant. Happy to wait for a re-review to merge if you want another look at it @JuliaKukulies @w-k-jones

**Comment by w-k-jones** [comment]
I'm happy to merge straight away, I don't think the fix requires a re-review as it looks like a pretty straightforward (and sensible) change

**Comment by w-k-jones** [comment]
Actually, as a workflow change, should this be merged into `RC_v1.5.x` or `main`?

**Comment by freemansw1** [comment]
Looks like #293 broke windows compatibility... will need to look into this before merging.

**Comment by JuliaKukulies** [comment]
> Looks like #293 broke windows compatibility... will need to look into this before merging.

Could that also be related to the change of dtypes in the feature detection/segmentation dataframes? What was the actual problem before you set these to constant in `utils.general.combine_feature_dataframes` ? Is that a thing we should consider doing in all functions that somehow modify the pandas dataframes?

**Comment by freemansw1** [comment]
> > Looks like #293 broke windows compatibility... will need to look into this before merging.
> 
> Could that also be related to the change of dtypes in the feature detection/segmentation dataframes? What was the actual problem before you set these to constant in `utils.general.combine_feature_dataframes` ? Is that a thing we should consider doing in all functions that somehow modify the pandas dataframes?

At first glance on my windows machine, it's not a datatype issue... rather the dataframe comes up empty (now, is this itself a result of a data type issue? Perhaps). I will work to debug here.

**Comment by freemansw1** [comment]
> > > Looks like #293 broke windows compatibility... will need to look into this before merging.
> > 
> > 
> > Could that also be related to the change of dtypes in the feature detection/segmentation dataframes? What was the actual problem before you set these to constant in `utils.general.combine_feature_dataframes` ? Is that a thing we should consider doing in all functions that somehow modify the pandas dataframes?
> 
> At first glance on my windows machine, it's not a datatype issue... rather the dataframe comes up empty (now, is this itself a result of a data type issue? Perhaps). I will work to debug here.

On second thought, I'm going to strongly bet that this is a time issue. Ugh. Times are going to be the death of me.

**Comment by freemansw1** [comment]
Okay, this was actually an amazing issue to fix. On Windows, the lines in the test dataset making that are:
https://github.com/tobac-project/tobac/blob/5f096e3e66da07cfd48a6a4588b993fc1263a0c2/tobac/testing.py#L435

result in a float output (with a real <1 value even!). When they are converted to xarray, xarray preserves the milliseconds contained in these values, but our Iris feature detection path does not use them, resulting in incompatible times. This was a neat issue to find actually! Anyway it's resolved now!

**Comment by JuliaKukulies** [comment]
Great job @freemansw1! Do you want to go ahead and merge this?

**Pull request merged**
