### PR TITLE
Wrap decorators to preserve docstrings and move to separate module

### LINKED ISSUE #356: Use `functools.wraps` to include docstrings in decorated functions
A function wrapped with a decorator will show the decorator's docstring, not the function that we want to see. We can use `functools.wraps` to handle this (see: https://docs.python.org/3/library/functools.html)

### PR DESCRIPTION
**Pull request by w-k-jones**
Resolves #356 and reorganises decorators to a separate module

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [x] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [x] Have you added NumPy docstrings for newly added functions? 
* [x] Have you formatted your code using black? 
* [x] If you have introduced a new functionality, have you added adequate unit tests?
* [x] Have all tests passed in your local clone? 
* [x] If you have introduced a new functionality, have you added an example notebook?
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged?

### CODE REVIEW

**Comment by w-k-jones** [comment]
Note that I wasn't able to use `functools.wrap` with the `njit_if_available` decorator because it works a bit differently to usual. If you have any ideas @freemansw1 let me know, but given that it's only used on internal functions I don't think the lack of docstrings when calling `help` is a problem, unlike with the xarray conversion decorators which wrap the main user functions

**Comment by freemansw1** [comment]
> Note that I wasn't able to use `functools.wrap` with the `njit_if_available` decorator because it works a bit differently to usual. If you have any ideas @freemansw1 let me know, but given that it's only used on internal functions I don't think the lack of docstrings when calling `help` is a problem, unlike with the xarray conversion decorators which wrap the main user functions

My guess is that this is done automagically through Numba; when I `return func` the correct docstring is also reported.

**Review by freemansw1 — APPROVED** [review]
Thanks for doing this, @w-k-jones ! I think you'll need to update before merge given #341 being merged, but I'm happy for you to merge after doing so.

**Review by JuliaKukulies — APPROVED** [review]

**Comment by JuliaKukulies** [comment]
Many thanks for this one, @w-k-jones! I think I have fixed the merge conflict now. If everything looks good, you can go ahead and merge

**Comment by JuliaKukulies** [comment]
Ready to merge @w-k-jones @freemansw1 ?  :)

**Pull request merged**
