### PR TITLE
Add DeprecationWarnings to several old functions

### LINKED ISSUE #198: Deprecating `wrapper.py` functions
I'd like to propose deprecating the functions in `wrapper.py` in v1.5, with a target of removing them in v2.0. These functions are just wrappers to run everything, and we don't use them in any of our documentation or examples.

### PR DESCRIPTION
**Pull request by freemansw1**
This PR is simply to add several DeprecationWarnings to various functions that have been discussed before as needing to be removed or substantially reworked for v2.0. Getting these DeprecationWarnings into v1.5 should give users enough time to migrate away from the functions. 

Resolves #198 and #158.

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [ ] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [ ] Have you added NumPy docstrings for newly added functions? 
* [x] Have you formatted your code using black? 
* [ ] If you have introduced a new functionality, have you added adequate unit tests?
* [ ] Have all tests passed in your local clone? 
* [ ] If you have introduced a new functionality, have you added an example notebook?
* [ ] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged?

### CODE REVIEW

**Review by snilsn — APPROVED** [review]
Nice work @freemansw1. After my experience with these functions I think that this step is the right way to go.

**Review by JuliaKukulies — APPROVED** [review]
Perfect, that makes sense @freemansw1. Thanks for your changes! Is there any clever way we can go about the coverage in pull requests like this or are we just ignoring it because we know we only added warnings?

**Comment by freemansw1** [comment]
@JuliaKukulies we have changed the code coverage threshold top -1% in #183, but I don't know that those changes have been merged back into v1.5.0 yet.

**Comment by freemansw1** [comment]
Thanks for the quick reviews!

**Comment by JuliaKukulies** [comment]
> @JuliaKukulies we have changed the code coverage threshold to -1% in #183, but I don't know that those changes have been merged back into v1.5.0 yet.

Right, sorry! I was aware of the change with #183 but misread and thought this would be even more than -1 %. There are probably a few things that haven't merged back yet, but I guess this will be done directly after the release so never mind

**Comment by freemansw1** [comment]
Yeah, now that we're so close to 1.4.0, I'm planning to wait to merge 1.4.0 into 1.5.0 until release.

**Pull request merged**
