### PR TITLE
Merge `RC_v1.5_hotfix` into `main`

### PR DESCRIPTION
**Pull request by w-k-jones**
Hotfix v1.5.1 release for issue with strict thresholding found in #314 and #315, fixed by #316

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [x] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [x] Have you added NumPy docstrings for newly added functions? 
* [x] Have you formatted your code using black? 
* [x] If you have introduced a new functionality, have you added adequate unit tests?
* [x] Have all tests passed in your local clone? 
* [x] If you have introduced a new functionality, have you added an example notebook?
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged?

### CODE REVIEW

**Comment by freemansw1** [comment]
Assuming #322 is resolved, I'm happy for this release to be pushed.

**Comment by w-k-jones** [comment]
> Assuming #322 is resolved, I'm happy for this release to be pushed.

We'll have to dig into the behaviour in #322 to see if anything is wrong or if that is expected behaviour. That may take a while, so perhaps if there is a fix needed there we should delay for a future release?

**Review by JuliaKukulies — APPROVED** [review]
Good to go! I agree that we can wait with #322 because it is also not clear for me if this is actually a bug.

**Review by freemansw1 — APPROVED** [review]
I am happy to merge/release!

**Review by freemansw1 — APPROVED** [review]
Now that #335 is in, I think this is ready for merge/release.

**Comment by freemansw1** [comment]
Ah, good catch on the changelog.

**Pull request merged**
