### PR TITLE
Correct parameter for the subnet size in adaptive search

### PR DESCRIPTION
**Pull request by snilsn**
This pull request aims at solving issue #133.

If neither adaptive_step nor adaptive_stop are given, **MAX_SUB_NET_SIZE** is set, otherwise **MAX_SUB_NET_SIZE_ADAPTIVE** is changed in the _linking_trackpy()_-function.

### CODE REVIEW

**Comment by freemansw1** [comment]
I've requested @JuliaKukulies and I as reviewers for this. I should be able to get to this next week. 

Once this is reviewed, it may make sense to release it as part of a 1.3.2 bugfix release. I'm hesitant to try to get it into 1.3.1, but I could see this and #124 for example making it into a 1.3.2 release. For now, I've kept it on the 1.5 milestone, but may move it to a new 1.3.2 milestone.

**Review by JuliaKukulies — COMMENTED** [review]
Thanks @snilsn, very good and careful observation! No objection from my side for the code changes you made. The only thing I wonder is whether we can add a more clear description for the `subnetwork_size` parameter in the docstrings? As I understand it, you would want it to be rather small when you do adaptive search and rather large when you do not. So this is important information the user needs to know.

**Review by freemansw1 — APPROVED** [review]
I'm happy with these changes. Good catch on finding the bug.

**Comment by freemansw1** [comment]
With the approving reviews, @snilsn please confirm that you're ready to merge and we will get this in `dev` with the intent to release as part of v1.3.2.

**Comment by snilsn** [comment]
Yes, from my side everything is ready for merging.

> The only thing I wonder is whether we can add a more clear description for the `subnetwork_size` parameter in the docstrings

I will adress this in an update of PR #138

**Review by JuliaKukulies — APPROVED** [review]

**Comment by JuliaKukulies** [comment]
Good, yes agreed that the documentation update is better for #138 ! Thanks!

**Pull request merged**
