### PR TITLE
Merge `main` into `dev`

### PR DESCRIPTION
**Pull request by JuliaKukulies**
I just realized that we have  missed to maintain the `dev` branch since we changed to the RC_* branches. If I understood it correctly, we want to keep `dev` to develop features and structural changes that are not specific milestones for the next release candidate. We therefore need to make sure that `dev` is up-to-date with `main`.

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [ ] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [ ] Have you added NumPy docstrings for newly added functions? 
* [ ] Have you formatted your code using black? 
* [ ] If you have introduced a new functionality, have you added adequate unit tests?
* [ ] Have all tests passed in your local clone? 
* [ ] If you have introduced a new functionality, have you added an example notebook?
* [ ] Have you kept your pull request small and limited so that it is easy to review? 
* [ ] Have the newest changes from this branch been merged?

### CODE REVIEW

**Comment by freemansw1** [comment]
I think the intent, rather than keeping the `dev` branch, was instead to create new `dev_*` branches, e.g., `dev_xarray` for specific features under development. I could be remembering wrong, @fsenf @w-k-jones @kelcyno thoughts?

**Comment by JuliaKukulies** [comment]
> I think the intent, rather than keeping the `dev` branch, was instead to create new `dev_*` branches, e.g., `dev_xarray` for specific features under development. I could be remembering wrong, @fsenf @w-k-jones @kelcyno thoughts?

Ah OK, sorry! That does actually make more sense and in that case I will close this pull request again. But to clarify: this mainly concerns some larger developments such as the transition to xarray, right? Or should all additions pass `dev_*` first?

**Comment by freemansw1** [comment]
I think this is only major changes and anything we want to work on collaboratively/iteratively.

**Comment by kelcyno** [comment]
@freemansw1 if we did away with dev entirely what would the pathway be for new PRs (that do not specifically address an xarray update etc)? For example, would I create a PR to main in the absence of a dev branch?

**Comment by JuliaKukulies** [comment]
> I think this is only major changes and anything we want to work on collaboratively/iteratively.

OK, thanks for the clarification! I will then close this again and we might think about deleting this branch to clean up things a bit :)

**Comment by JuliaKukulies** [comment]
> @freemansw1 if we did away with dev entirely what would the pathway be for new PRs (that do not specifically address an xarray update etc)? For example, would I create a PR to main in the absence of a dev branch?

If I understood it correctly, you would continue creating PRs for the respective RC_* branch.

**Comment by JuliaKukulies** [comment]
And one more question, @freemansw1: would it make more sense for things such as the developer guide to create a dev_* branch or create a branch from RC_* in my fork that I share with @fsenf such that we can work collaboratively before submitting a PR? 

I am just thinking that there might be some collaborative efforts (especially for documentation), where the development would slow down a lot if each change needs to go via a PR. In that case, I would maybe only request @fsenf as a reviewer first, but still.

**Comment by JuliaKukulies** [comment]
And one more question, @freemansw1, @kelcyno : would it make more sense for things such as the developer guide to create a dev_* branch or create a branch from RC_* in my fork that @fsenf can directly commit to such that we can work collaboratively before submitting a PR or simply create a PR for dev_* that is only draft and that both can directly commit into? 

I am just thinking that there might be some collaborative efforts (especially for documentation), where the development would slow down a lot if each change needs to go via a PR. In that case, I would maybe only request @fsenf as a reviewer first, but still.

**Comment by freemansw1** [comment]
> And one more question, @freemansw1, @kelcyno : would it make more sense for things such as the developer guide to create a dev_* branch or create a branch from RC_* in my fork that @fsenf can directly commit to such that we can work collaboratively before submitting a PR or simply create a PR for dev_* that is only draft and that both can directly commit into?
> 
> I am just thinking that there might be some collaborative efforts (especially for documentation), where the development would slow down a lot if each change needs to go via a PR. In that case, I would maybe only request @fsenf as a reviewer first, but still.

I think that doing something like that through a `dev_*` branch (or even an `exp_*` branch) on the main repository would be appropriate. In fact, I think we should encourage collaborative efforts like that to exist on the `dev_*` branches!

**Comment by JuliaKukulies** [comment]
> > And one more question, @freemansw1, @kelcyno : would it make more sense for things such as the developer guide to create a dev_* branch or create a branch from RC_* in my fork that @fsenf can directly commit to such that we can work collaboratively before submitting a PR or simply create a PR for dev_* that is only draft and that both can directly commit into?
> > I am just thinking that there might be some collaborative efforts (especially for documentation), where the development would slow down a lot if each change needs to go via a PR. In that case, I would maybe only request @fsenf as a reviewer first, but still.
> 
> I think that doing something like that through a `dev_*` branch (or even an `exp_*` branch) on the main repository would be appropriate. In fact, I think we should encourage collaborative efforts like that to exist on the `dev_*` branches!

OK, thank you! I agree and maybe this case (and in general cases of extensive documentation enhancements with long text) could be an exp_* case then because that would allow changes to be merged without any reviews.

**Pull request closed without merging**
