### PR TITLE
updated v1.5 reference to peer-reviewed 

### PR DESCRIPTION
**Pull request by JuliaKukulies**
Updated the reference and thereby solved #445

### CODE REVIEW

**Comment by w-k-jones** [comment]
It would be nice to add the publications to the top of the "Refereed Publications" page, but I'm happy to approve this as is

**Comment by JuliaKukulies** [comment]
> It would be nice to add the publications to the top of the "Refereed Publications" page, but I'm happy to approve this as is

Agree, I will add this!

**Review by w-k-jones — APPROVED** [review]

**Review by freemansw1 — APPROVED** [review]
Thanks, @JuliaKukulies. For the issue in utils, is there an issue number linked to it? If so, let's make sure to mark it with the milestone and close it too.

**Comment by JuliaKukulies** [comment]
> Thanks, @JuliaKukulies. For the issue in utils, is there an issue number linked to it? If so, let's make sure to mark it with the milestone and close it too.

As for the utils fixes:  this was done in the already closed PR of Will #451 (issue #444). It just ended up here as well since there was a time mismatch and I have then merged in the changes from #451 to this PR so the matrix testing is fixed

**Comment by JuliaKukulies** [comment]
@freemansw1 Since the issue that was related to these merged in changes is closed, I am merging this now

**Pull request merged**
