### PR TITLE
Add code coverage via Github Actions

### LINKED ISSUE #94: Add Code Coverage to `main` and `dev`
Based on a discussion with @w-k-jones and @galexsky, we should probably add code coverage to the `main` and `dev` branches to encourage more tests to be added. I'm happy to add it in the same way that we have it on `v2.0-dev`.

### PR DESCRIPTION
**Pull request by freemansw1**
Resolves #94 and adds code coverage via codecov.io and GitHub Actions. 

We will want to merge this as a squash merge.

### CODE REVIEW

**Comment by freemansw1** [comment]
Apologies for spamming your email with the failed attempts here; this ended up being nontrivial.

**Comment by freemansw1** [comment]
Note that we can turn those coverage comments off (I like them, and am happy for them to be on).

**Review by JuliaKukulies — APPROVED** [review]
Nice, well done @freemansw1! It looks all good to me. Yes, probably a good idea to squash the commits. I also like the comments and think it could be useful to leave them on. I assume that the issue with the missing base report will be automatically fixed when the PR is merged?

**Comment by freemansw1** [comment]
Thanks @JuliaKukulies! Yes, it should be the comparison version, but since this has never been run before, there's nothing to compare to.

**Comment by freemansw1** [comment]
I am inclined to go ahead and merge this after #141 is resolved and 1.3.1 is out, unless you think we should try to get it in for 1.3.1 @JuliaKukulies?

**Comment by JuliaKukulies** [comment]
I think that sounds like a good plan, especially when there will be an extra bug fix release 1.3.2, it can be released together with #140 as you suggested (and I think it would make sense and we do not need to wait for #140 to be reviewed to release 1.3.1).

**Pull request merged**
