### PR TITLE
Fix 2d coordinate interpolation

### PR DESCRIPTION
**Pull request by w-k-jones**
Fixes the problem with 2d coordinate interpolation producing `object` dtypes in feature_detection raised in #240 that was the cause of the bug in #239 

Ideally this could be released as part of v1.4.2, but the changes to the utils structure as part of v1.5 make it impractical to separate

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [x] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [x] Have you added NumPy docstrings for newly added functions? 
* [x] Have you formatted your code using black? 
* [ ] If you have introduced a new functionality, have you added adequate unit tests?
* [x] Have all tests passed in your local clone? 
* [ ] If you have introduced a new functionality, have you added an example notebook?
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged?

### CODE REVIEW

**Review by JuliaKukulies — APPROVED** [review]
Looks good. Yes true, it will be a bit of a pain to  merge this back to v1.5 with the utils module split. However, I think we should go for it nonetheless, since it makes sense to include this in v1.4.2 as you say

**Review by freemansw1 — APPROVED** [review]
I'm happy with this, thanks for the bugfix! I agree that 1.4.2 would be better but I'm happy to wait until 1.5.0 if it's a pain. 1.5.0 in theory shouldn't be far behind.

**Comment by freemansw1** [comment]
Once #251 is merged, I think this PR can be closed, right?

**Comment by w-k-jones** [comment]
I don't think the changes got moved across to the v1.5 branch due to the change in the utils submodule structure, so I'll wait until #257 is merged and then see if this can be closed or merged

**Comment by freemansw1** [comment]
Yeah, good point @w-k-jones! Let's get this merged (after #257).

**Comment by JuliaKukulies** [comment]
#257 merged, good to go!

**Pull request merged**
