### PR TITLE
Added missing test for get_spacings

### PR DESCRIPTION
**Pull request by fziegner**
This PR addresses #425 and adds a test for the get_spacings function.

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [x] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [x] Have you added NumPy docstrings for newly added functions? 
* [x] Have you formatted your code using black? 
* [x] If you have introduced a new functionality, have you added adequate unit tests?
* [ ] Have all tests passed in your local clone? 
* [ ] If you have introduced a new functionality, have you added an example notebook?
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged?

### CODE REVIEW

**Review by fsenf — APPROVED** [review]
@fziegner : Thank you! The test looks good and runs smoothly. It is ready to be merged!

**Review by JuliaKukulies — APPROVED** [review]
Looking good, thanks @fziegner !

**Comment by freemansw1** [comment]
@fziegner are you happy for this to be merged?

**Comment by fziegner** [comment]
@freemansw1 Yes, I am.

**Pull request merged**
