### PR TITLE
fixed duplicate index issue in test_trackpy_predict

### PR DESCRIPTION
**Pull request by JuliaKukulies**
Fixes issue related to non-unique index values in dataframes for testing.
Solves #342 

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [ ] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [ ] Have you added NumPy docstrings for newly added functions? 
* [x] Have you formatted your code using black? 
* [x] If you have introduced a new functionality, have you added adequate unit tests?
* [x] Have all tests passed in your local clone? 
* [ ] If you have introduced a new functionality, have you added an example notebook?
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged?

### CODE REVIEW

**Review by freemansw1 — APPROVED** [review]

**Comment by freemansw1** [comment]
Thanks for knocking this out, @JuliaKukulies !

**Comment by JuliaKukulies** [comment]
Thanks for the quick review @freemansw1 ! I'll let @w-k-jones or @kelcyno have a look before I merge. I guess the best strategy would be to do a re-release for `v1.5.1` then since this version hasnt been released on conda yet?

**Comment by freemansw1** [comment]
> Thanks for the quick review @freemansw1 ! I'll let @w-k-jones or @kelcyno have a look before I merge. I guess the best strategy would be to do a re-release for `v1.5.1` then since this version hasnt been released on conda yet? In that case, I could also just go ahead and merge and require a double-review before merging to main.

I think that's our only option, yeah. Or we can call it `v1.5.1a`. I wonder if you shouldn't just change the target of the PR straight to `main` given the incongruity; then we could wait for a second reviewer and skip the second merge.

**Review by w-k-jones — APPROVED** [review]

**Comment by w-k-jones** [comment]
Thanks for fixing this @JuliaKukulies! I agree with Sean, let's merge this straight into main and then I can do a rerelease and sort out the conda side of things...

**Comment by JuliaKukulies** [comment]
OK, sounds good! Thank you both!

**Pull request merged**
