### PR TITLE
Solving the bug in API docs rendering

### PR DESCRIPTION
**Pull request by fsenf**
* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [x] Have you written documentation that is easy to understand?
* [ ] Have you written descriptive commit messages? 
* [ ] Have you added NumPy docstrings for newly added functions? 
* [ ] Have you formatted your code using black? 
* [ ] If you have introduced a new functionality, have you added adequate unit tests?
* [ ] Have all tests passed in your local clone? 
* [ ] If you have introduced a new functionality, have you added an example notebook?
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged? 

This solve the RTD rendering bug:
- included `numpy` in installation requirement and exclude `numpy` from mock list
- made a short documentation how to run sphinx-based rendering locally
- this solves #297

### CODE REVIEW

**Review by JuliaKukulies — COMMENTED** [review]
This works well and fixes the API. I am fine with this change, but want to double check with @freemansw1 and @w-k-jones if this is the preferred fix, as I am not sure if there are any significant adverse implications of making `numpy` a dependency instead of mocking it. 

Also, we might want to add `tobac.utils.internal` and `tobac.utils.periodic_boundary`to `doc/tobac.rst` and I am wondering if `Testing-Sphinx-based-Rendering.md` is something for the developer guide.

**Review by freemansw1 — COMMENTED** [review]
Thanks so much for taking care of this, @fsenf. I'm happy with the PR, but have the same thought as @JuliaKukulies on moving the testing into the developer guide. 

As long as RTD is happy with installing numpy instead of mocking it, I'm happy to do that.

**Comment by fsenf** [comment]
OK, good suggestion! I will update the PR and remove the markdown-based description in this PR. 

To have a homogeneous format, I will convert the .md file to .rst and directly add it to PR #281.

**Review by freemansw1 — APPROVED** [review]
Thanks, @fsenf. I'm happy with this now!

**Review by JuliaKukulies — APPROVED** [review]
Me too :) ready to merge!

**Review by freemansw1 — APPROVED** [review]

**Comment by fsenf** [comment]
Nice, now I feel confident to push the green button.

**Pull request merged**
