### PR TITLE
updated docstrings for n_min_threshold

### PR DESCRIPTION
**Pull request by JuliaKukulies**
Solves #427 

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [x] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [x] Have you added NumPy docstrings for newly added functions? 
* [x] Have you formatted your code using black? 
* [x] If you have introduced a new functionality, have you added adequate unit tests?
* [x] Have all tests passed in your local clone? 
* [x] If you have introduced a new functionality, have you added an example notebook?
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged?

### CODE REVIEW

**Review by freemansw1 — APPROVED** [review]
Thanks,  @JuliaKukulies .

**Comment by fsenf** [comment]
@fziegner can jump in here and do the 2nd review if it is fine for @kelcyno

**Comment by JuliaKukulies** [comment]
> @fziegner can jump in here and do the 2nd review if it is fine for @kelcyno 

That'd be awesome :)

**Review by fziegner — APPROVED** [review]
Looks good to me.

**Comment by fziegner** [comment]
Something I overlooked: it might be good to change the type hint to `Union[int, dict[float, int], list[int]] = 0` and docstring to `n_min_threshold : int, dict of float to int, or list of int, optional` as it's done the same for other variables.

**Comment by JuliaKukulies** [comment]
Thanks @fziegner! I have addressed your comments now and will merge once the tests have passed :)

**Pull request merged**
