### PR TITLE
Reimplimentation of strict thresholding

### PR DESCRIPTION
**Pull request by w-k-jones**
Fix for the bugs identified in strict thresholding in #314 and #315 . Strict thresholding is now handled in `remove_parents`, by removing features which do not have parents, rather than by modifying the input data.

- Strict thresholding now works for `target="minimum"`
- Strict thresholding produces identical results to non-stric thresholding if `n_min_threshold` is a fixed value
- New tests added for strict thresholding

* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [x] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [x] Have you added NumPy docstrings for newly added functions? 
* [x] Have you formatted your code using black? 
* [x] If you have introduced a new functionality, have you added adequate unit tests?
* [x] Have all tests passed in your local clone? 
* [x] If you have introduced a new functionality, have you added an example notebook?
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged?

### CODE REVIEW

**Review by JuliaKukulies — APPROVED** [review]
This looks all good to me and I am happy with letting `remove_parents` take care of the strict thresholding. Great solution @w-k-jones !

**Comment by w-k-jones** [comment]
Thanks! In future we should possibly either rename `remove_parents` or split it into multiple methods that handle operations involving features and their parents to reflect its wider responsibility, but this can wait until a later refactor

**Review by harrietgilmour — APPROVED** [review]
This all looks good! I also tested new implementation with own data and it appears to be working as expected. There are no longer tracks detected at a lower minimum value than the `dataset.min()` when using `threshold='minimum'` and `strict_thresholding=True`. It also produces the same number of tracks when using a single `nminthreshold` with `strict_thresholding=True` and `strict_thresholding=False`.  Thanks for sorting this out :)

**Comment by w-k-jones** [comment]
> This all looks good! I also tested new implementation with own data and it appears to be working as expected. There are no longer tracks detected at a lower minimum value than the `dataset.min()` when using `threshold='minimum'` and `strict_thresholding=True`. It also produces the same number of tracks when using a single `nminthreshold` with `strict_thresholding=True` and `strict_thresholding=False`. Thanks for sorting this out :)

Thanks for the review! I'll merge now

**Pull request merged**
