### PR TITLE
Feature: Only detect features if all previous thresholds have been met

### PR DESCRIPTION
**Pull request by lettlini**
* [x] Have you followed our guidelines in CONTRIBUTING.md? 
* [x] Have you self-reviewed your code and corrected any misspellings? 
* [x] Have you written documentation that is easy to understand?
* [x] Have you written descriptive commit messages? 
* [x] Have you added NumPy docstrings for newly added functions? 
* [x] Have you formatted your code using black? 
* [ ] If you have introduced a new functionality, have you added adequate unit tests?
* [x] Have all tests passed in your local clone? 
* [ ] If you have introduced a new functionality, have you added an example notebook?
* [x] Have you kept your pull request small and limited so that it is easy to review? 
* [x] Have the newest changes from this branch been merged? 

This PR introduces the ability to only detect features if all previous thresholds have been met as discussed in #261.

### CODE REVIEW

**Comment by w-k-jones** [comment]
@freemansw1 should we aim to include this in v1.5 so that it does not clash with the shift to xarray for v1.6?

**Comment by freemansw1** [comment]
> @freemansw1 should we aim to include this in v1.5 so that it does not clash with the shift to xarray for v1.6?

If we can do it quickly. I am disinclined from adding more that we need to wait on. If we decide to wait on this, we can always include a minor feature like this in a v1.5.x release before v1.6.

**Comment by lettlini** [comment]
I think I will need some more time to polish this PR (e.g. add unit tests). Therefore, I would be in favor of including this in a minor release as @freemansw1  suggested.

**Comment by w-k-jones** [comment]
@lettlini are you happy if I add the fix for #298 to this PR? I think it will require changing the order in which `remove_parents` and your additions are performed in, so I think it will be easier to avoid conflicts if I commit the changes  to your branch

**Comment by lettlini** [comment]
> @lettlini are you happy if I add the fix for #298 to this PR? I think it will require changing the order in which `remove_parents` and your additions are performed in, so I think it will be easier to avoid conflicts if I commit the changes to your branch

absolutely no problem, Thank you @w-k-jones

**Comment by w-k-jones** [comment]
Have created a PR for this change at https://github.com/lettlini/tobac/pull/1#issue-1751115044

**Review by JuliaKukulies — APPROVED** [review]
Nice job, @lettlini! I had a detailed look at both the unit test and the example notebook and I think they are both clear and make sense. So approved from my side. 

Also, nice catch on the `remove_parents` bug @w-k-jones !

**Comment by freemansw1** [comment]
Just noting that we should hold off on merging this until #298 is resolved.

**Comment by w-k-jones** [comment]
> Just noting that we should hold off on merging this until #298 is resolved.

Apologies, I should have been a bit more explicit. #298 is resolved within this PR, as I added it directly to Kolya's branch to avoid any conflicts (see lettlini#1)

**Review by freemansw1 — APPROVED** [review]
Thanks @w-k-jones for the clarification. I'm happy for this to be merged, then!

**Pull request merged**
